spring:
  application:
    name: board-practice
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: local